// <auto-generated />
using System;
using BookMS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookMS.Migrations
{
    [DbContext(typeof(AppDbContent))]
    partial class AppDbContentModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("BookMS.Models.Admin", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = "admin",
                            Password = "admin"
                        });
                });

            modelBuilder.Entity("BookMS.Models.Book", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Press")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = "978-7-302-34695-1",
                            Author = "尹为民",
                            Name = "数据库原理与技术",
                            Number = 20,
                            Press = "清华大学出版社"
                        },
                        new
                        {
                            Id = "978-7-111-50482-5",
                            Author = "David A. Patterson",
                            Name = "计算机组成与设计",
                            Number = 10,
                            Press = "机械工业出版社"
                        });
                });

            modelBuilder.Entity("BookMS.Models.Lend", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bid")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("LendTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime");

                    b.Property<string>("Uid")
                        .HasColumnType("varchar(767)");

                    b.HasKey("No");

                    b.HasIndex("Bid");

                    b.HasIndex("Uid");

                    b.ToTable("Lends");
                });

            modelBuilder.Entity("BookMS.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<bool>("Sex")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "wzy",
                            Name = "万兆奕",
                            Password = "wzy",
                            Sex = true
                        },
                        new
                        {
                            Id = "shr",
                            Name = "宋昊睿",
                            Password = "shr",
                            Sex = true
                        });
                });

            modelBuilder.Entity("BookMS.Models.Lend", b =>
                {
                    b.HasOne("BookMS.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("Bid");

                    b.HasOne("BookMS.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("Uid");

                    b.Navigation("Book");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
